name: 404-base-miner-env
channels: 
  - conda-forge
  - nvidia
  - defaults

dependencies: 
  - python=3.11
  - pip
  - cuda-toolkit=12.8.0
  - cudnn=9.3
  - gcc=14.2.0
  - gxx=14.2.0
  - gcc_linux-64=14.2.0
  - lld=19.1.7
  - cmake=4.2.1
  - ninja=1.13.0
  - zstd
  - pybind11=3.0.1
  - libjpeg-turbo=3.1.2
  - zlib=1.3.1
  - pip:
      - -r requirements.txt